import { sql } from "drizzle-orm";
import { db } from "@workspace/db";

/**
 * Render can start an existing service with a dashboard-configured command
 * instead of the latest render.yaml command. Keep the loyalty schema safe to
 * initialize at boot so the first streak request cannot race a migration.
 */
export async function ensureStreakSchema(): Promise<void> {
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS streak_prizes (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name text NOT NULL,
      description text,
      prize_type text NOT NULL,
      discount_percent integer,
      free_item_name text,
      custom_description text,
      min_days_required integer NOT NULL DEFAULT 4,
      cycle_length_days integer NOT NULL DEFAULT 7,
      streak_mode text NOT NULL DEFAULT 'window',
      is_active boolean NOT NULL DEFAULT true,
      branch_id integer REFERENCES branches(id),
      created_at timestamptz NOT NULL DEFAULT now()
    )
  `);

  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS customer_streaks (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      customer_phone text NOT NULL,
      customer_name text,
      streak_code text NOT NULL UNIQUE,
      branch_id integer REFERENCES branches(id),
      cycle_start_date date NOT NULL,
      cycle_end_date date NOT NULL,
      active_days integer NOT NULL DEFAULT 0,
      active_day_dates jsonb NOT NULL DEFAULT '[]'::jsonb,
      streak_mode text NOT NULL DEFAULT 'window',
      status text NOT NULL DEFAULT 'active',
      prize_id integer REFERENCES streak_prizes(id),
      won_at timestamptz,
      notified_at timestamptz,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now()
    )
  `);

  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS streak_active_days (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      streak_id integer NOT NULL REFERENCES customer_streaks(id),
      active_date date NOT NULL,
      order_id integer REFERENCES orders(id),
      recorded_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT streak_active_days_streak_date_unique UNIQUE (streak_id, active_date)
    )
  `);

  await db.execute(sql`
    ALTER TABLE customers
      ADD COLUMN IF NOT EXISTS streak_code text,
      ADD COLUMN IF NOT EXISTS current_streak_id integer
  `);

  await db.execute(sql`
    CREATE UNIQUE INDEX IF NOT EXISTS customers_streak_code_idx
      ON customers (streak_code)
      WHERE streak_code IS NOT NULL
  `);

  // Fresh Render databases need the same usable defaults as development.
  await db.execute(sql`
    INSERT INTO streak_prizes
      (name, description, prize_type, min_days_required, cycle_length_days, streak_mode, is_active)
    SELECT 'Free Meal', 'One free meal of your choice', 'free_meal', 7, 7, 'window', true
    WHERE NOT EXISTS (SELECT 1 FROM streak_prizes)
  `);
  await db.execute(sql`
    INSERT INTO streak_prizes
      (name, description, prize_type, discount_percent, min_days_required, cycle_length_days, streak_mode, is_active)
    SELECT '50% Discount', '50% off your next order', 'discount_percent', 50, 4, 7, 'window', true
    WHERE NOT EXISTS (SELECT 1 FROM streak_prizes WHERE name = '50% Discount')
  `);
}